const WHATSAPP='212600000000';
let products=[], cart=[], current=null;
const demo=[
{name:'Caftan Émeraude',category:'caftan',price:1890,desc:'Caftan marocain élégant aux finitions raffinées.',mark:'✦'},
{name:'Takchita Royale',category:'takchita',price:2490,desc:'Takchita deux pièces pensée pour les grandes occasions.',mark:'◇'},
{name:'Caftan Sable',category:'caftan',price:1590,desc:'Silhouette contemporaine et détails inspirés du patrimoine.',mark:'✧'},
{name:'Parure Tradition',category:'accessoire',price:390,desc:'Accessoire doré pour compléter votre tenue.',mark:'❖'},
{name:'Jellaba Signature',category:'accessoire',price:790,desc:'Jellaba marocaine chic et confortable.',mark:'✦'},
{name:'Ceinture Mdamma',category:'accessoire',price:290,desc:'Détail précieux pour structurer la silhouette.',mark:'◇'},
{name:'Takchita Ivoire',category:'takchita',price:2190,desc:'Une pièce lumineuse pour vos cérémonies.',mark:'✧'},
{name:'Caftan Nuit',category:'caftan',price:1790,desc:'Élégance profonde et finitions couture.',mark:'❖'}];

function money(n){return Number(n).toLocaleString('fr-MA')+' DH'}
function escapeHtml(s){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function render(list=products){const el=document.getElementById('products');el.innerHTML=list.map((p,i)=>`<article class="product-card" data-i="${products.indexOf(p)}"><button class="quick">Voir la pièce</button><div class="product-img">${p.image?`<img src="${escapeHtml(p.image)}" alt="${escapeHtml(p.name)}">`:`<span>${p.mark||'✦'}</span>`}</div><div class="product-info"><div class="product-cat">${escapeHtml(p.category)}</div><h3>${escapeHtml(p.name)}</h3><div class="product-price">${money(p.price)}</div></div></article>`).join('');el.querySelectorAll('.product-card').forEach(c=>c.onclick=()=>openProduct(products[c.dataset.i]))}
async function load(){try{const r=await fetch('/api/products');const d=await r.json();if(d.ok&&d.products?.length)products=d.products.map(p=>({name:p.Nom||p.Name||p.Produit||'Pièce Maison SB',category:String(p.Categorie||p.Category||'caftan').toLowerCase(),price:Number(p.Prix||p.Price||0),desc:p.Description||p.Desc||'',image:p.ImageURL||p.Image||p.Photo||'',mark:'✦'}));else products=demo}catch(e){products=demo}render();}
function openProduct(p){current=p;document.getElementById('modalCategory').textContent=p.category;document.getElementById('modalName').textContent=p.name;document.getElementById('modalDesc').textContent=p.desc;document.getElementById('modalPrice').textContent=money(p.price);document.getElementById('modalQty').value=1;document.getElementById('modalPhoto').innerHTML=p.image?`<img src="${escapeHtml(p.image)}" alt="${escapeHtml(p.name)}">`:`<span>${p.mark||'✦'}</span>`;document.getElementById('productModal').classList.add('open')}
function closeModal(){document.getElementById('productModal').classList.remove('open')}
function updateCart(){document.getElementById('cartCount').textContent=cart.reduce((a,x)=>a+x.qty,0);document.getElementById('cartItems').innerHTML=cart.length?cart.map((x,i)=>`<div class="cart-row"><span>${escapeHtml(x.name)} × ${x.qty}</span><span>${money(x.price*x.qty)} <button class="remove" data-i="${i}">×</button></span></div>`).join(''):'<p style="color:#777;font-size:12px">Votre panier est vide.</p>';document.querySelectorAll('.remove').forEach(b=>b.onclick=()=>{cart.splice(Number(b.dataset.i),1);updateCart()});document.getElementById('cartTotal').textContent=money(cart.reduce((a,x)=>a+x.price*x.qty,0))}
function openCart(){document.getElementById('cart').classList.add('open');document.getElementById('backdrop').classList.add('open')}
function closeCart(){document.getElementById('cart').classList.remove('open');document.getElementById('backdrop').classList.remove('open')}
document.getElementById('filters').onclick=e=>{const b=e.target.closest('button');if(!b)return;document.querySelectorAll('.filters button').forEach(x=>x.classList.remove('active'));b.classList.add('active');const f=b.dataset.filter;render(f==='all'?products:products.filter(p=>p.category.includes(f)))};
document.getElementById('cartBtn').onclick=openCart;document.getElementById('closeCart').onclick=closeCart;document.getElementById('backdrop').onclick=closeCart;document.getElementById('closeModal').onclick=closeModal;document.getElementById('productModal').onclick=e=>{if(e.target.id==='productModal')closeModal()};
document.getElementById('addModal').onclick=()=>{const qty=Math.max(1,Number(document.getElementById('modalQty').value)||1);const old=cart.find(x=>x.name===current.name);old?old.qty+=qty:cart.push({...current,qty});updateCart();closeModal();openCart()};
document.getElementById('orderBtn').onclick=()=>{if(!cart.length)return alert('Votre panier est vide.');const lines=cart.map(x=>`• ${x.name} × ${x.qty} = ${money(x.price*x.qty)}`).join('%0A');const total=money(cart.reduce((a,x)=>a+x.price*x.qty,0));window.open(`https://wa.me/${WHATSAPP}?text=Bonjour Maison SB,%0AJe souhaite commander:%0A${lines}%0ATotal: ${total}%0AMerci.` ,'_blank')};
document.getElementById('whatsappContact').href=`https://wa.me/${WHATSAPP}?text=Bonjour Maison SB, je souhaite avoir des informations sur vos caftans.`;load();updateCart();